### ISSUE TITLE
可以增加个关闭 notification 的选项吗？

### ISSUE THREAD

**Issue by hellodword** [AlanAlbert/musicfox#4]

**Comment by anhoder** [comment]
现在musicfox还存在一些使用上的不好解决的问题（例如，出现跳歌、不能播放无损歌曲等），我正考虑在2.0版本使用go来重写它，到时候新功能将会在新仓库中提交，所以这个仓库暂时不会加入新功能，抱歉😅

**Comment by hellodword** [comment]
> 现在musicfox还存在一些使用上的不好解决的问题（例如，出现跳歌、不能播放无损歌曲等），我正考虑在2.0版本使用go来重写它，到时候新功能将会在新仓库中提交，所以这个仓库暂时不会加入新功能，抱歉😅

这样啊，那我不折腾 pr 了。。。

跨平台 TUI 程序用 go 确实是个好选择，期待 2.0

**Comment by anhoder** [comment]
## musicfox 2.0已经发布✨✨✨

使用go进行重写，传送门：[go-musicfox](https://github.com/anhoder/go-musicfox)
